### ISSUE TITLE
ImportError: cannot import name RGBColor

### ISSUE THREAD

**Issue by anitamazur** [joar/py-colorclassifier#1]
Hello,

I executed your script with python3 in a terminal and I got this error :

> > > from colorclassifier import Classifier
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "colorclassifier/**init**.py", line 21, in <module>
> > >     from colormath.color_objects import LabColor, RGBColor
> > > ImportError: cannot import name RGBColor

I saw that colormath has changed some function names.

I had to change the following line in your script called **init**.py :
from colormath.color_objects import LabColor, RGBColor

to :
from colormath.color_objects import LabColor, sRGBColor

Now, colormath is correctly imported.

Best regards,
anita mazur

**Comment by anitamazur** [comment]
Hello again,

I saw that there is a fork of this project.
The forked version have this issue fixed : https://github.com/tttallis/py-colorclassifier

Best regards,
anita mazur
